### ISSUE TITLE
Enhancement Request: Option to reference an existing secret for API Key or Bearer Token

### ISSUE THREAD

**Issue by asjonos** [OctopusDeploy/helm-charts#228]
It would be beneficial to add functionality allowing the referencing of an existing secret that holds an API key or a bearer token.

```
agent:
  existingApiKeySecret: my-secret-name
  existingBearerTokenSecret: my-secret-name
```

In the existing tentacle-deployment.yaml, we have:
```
            {{- if .Values.agent.serverApiKey }}
            - name: "ServerApiKey"
              valueFrom:
                secretKeyRef: 
                  name: {{ include "kubernetes-agent.secrets.serverAuth" . }}
                  key: api-key
            {{- end }}
            {{- if .Values.agent.bearerToken }}
            - name: "BearerToken"
              valueFrom:
                secretKeyRef: 
                  name: {{ include "kubernetes-agent.secrets.serverAuth" . }}
                  key: bearer-token
            {{- end }}
```
Add something to support the use of existing secrets:
```
            {{- if .Values.agent.existingApiKeySecret }}
            - name: "ServerApiKey"
              valueFrom:
                secretKeyRef: 
                  name: {{ .Values.agent.existingApiKeySecret }}
                  key: api-key
            {{- end }}
            {{- if .Values.agent.existingBearerTokenSecret }}
            - name: "BearerToken"
              valueFrom:
                secretKeyRef: 
                  name: {{ .Values.agent.existingBearerTokenSecret }}
                  key: bearer-token
            {{- end }}
```
Additionally, the tentacle-server-auth-secret.yaml must only be created if neither existingApiKeySecret nor existingBearerTokenSecret is set.
