### ISSUE TITLE
Affinity indention error in Ocotpus server chart

### ISSUE THREAD

**Issue by dmitrii-didenko** [OctopusDeploy/helm-charts#244]
Hello!

There is an issue with affinity block in octopus server chart. Testing with the following values.yaml:
```
affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
            - key: app.kubernetes.io/component
              operator: In
              values:
                - ingester
        topologyKey: kubernetes.io/hostname
```
This throws an error: "error converting YAML to JSON: yaml: line 26: did not find expected key"

This is because of indention and combination of "{{" and `indent` instead of `nindent` in the statefulset template

My suggestion is to fix this the way it was fixed for tolerations, just by moving block to the left:
```
      {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
      {{- end }}
    {{- with .Values.octopus.tolerations }}
```
then, it shuld work, I've tested.
