### ISSUE TITLE
Allow setting security context and octopus server configuration directory

### ISSUE THREAD

**Issue by grace-rehn** [OctopusDeploy/helm-charts#378]
Users would like to be able to set security context settings when installing Octopus Deploy with helm charts.

```
  securityContext:
        fsGroup: 999
        fsGroupChangePolicy: OnRootMismatch
        runAsGroup: 999
        runAsNonRoot: true
        runAsUser: 999
```

When running with the security context above, users would also like to set the octopus server configuration directory.

Internal requests:
https://octopus.zendesk.com/agent/tickets/224342
https://octopus.zendesk.com/agent/tickets/219068
