### ISSUE TITLE
ingress template annotations indentation typo

### ISSUE THREAD

**Issue by ice-8** [OctopusDeploy/helm-charts#411]
`charts/octopus-deploy/templates/ingress.yaml` contains typo at [line 13](https://github.com/OctopusDeploy/helm-charts/blob/25d103d26c7fd7c21e7136388533805f2bddd9da/charts/octopus-deploy/templates/ingress.yaml#L13)

How to reproduce:
1. create values.yaml
```
octopus:
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: "name-cluster-issuer"
      cert-manager.io/duration: "24h"

mssql:
  enabled: true
```
2. run
```
helm template my-octopus-instance oci://ghcr.io/octopusdeploy/octopusdeploy-helm -f values.yaml
Pulled: ghcr.io/octopusdeploy/octopusdeploy-helm:1.3.1
Digest: sha256:91d25397c382e033c6a1521b8f73f83c306784f746372fcda840d4edb496463b
Error: YAML parse error on octopusdeploy-helm/templates/ingress.yaml: error converting YAML to JSON: yaml: line 10: mapping values are not allowed in this context

Use --debug flag to render out invalid YAML
```
