### ISSUE TITLE
acceptEula value not working

### ISSUE THREAD

**Issue by HW-Jeremy** [OctopusDeploy/helm-charts#96]
Hello,

the acceptEula parameter doesn't work, here is my values.yml :

```
octopus:
  image:
    tag: "2024.1.12163"
  acceptEula: "Y" # It is required to accept the Octopus EULA https://octopus.com/legal/customer-agreement
  masterKey: XXX
  databaseConnectionString: XXX
  licenseKeyBase64: XXX
  email: "xxx"
  taskCap: 5
  serverLogVolume:
    size: 1Gi
    storageClassName: "azurefile"
    storageAccessMode: ReadWriteOnce 
  packageRepositoryVolume:
    size: 1Gi 
    storageClassName: "azurefile"
    storageAccessMode: ReadWriteOnce
  # The volume used for persisting deployment artifacts: https://octopus.com/docs/projects/deployment-process/artifacts
  artifactVolume:
    size: 1Gi 
    storageClassName: "azurefile"
    storageAccessMode: ReadWriteOnce
 # Volume used for task logs: https://octopus.com/docs/support/get-the-raw-output-from-a-task
  taskLogVolume: 
    size: 1Gi 
    storageClassName: "azurefile"
    storageAccessMode: ReadWriteOnce
```

Here's the error I get:

`json : cannot unmarshal bool into Go struct field EnvVar.spec.template.spec.containers.env.value of type string`

That's because the Y isn't in quotation marks:

`helm template octopus-deploy  oci://registry-1.docker.io/octopusdeploy/octopusdeploy-helm --values values.yml` give me :

```
---
# Source: octopusdeploy-helm/templates/statefulset.yaml
# Octopus Deploy server nodes are modeled as StatefulSet, as terminating a node while deployments or runbooks are executing will cause these tasks to be terminated
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: octopus-deploy
  labels:
    app: octopus-deploy
    chart: octopusdeploy-helm-2023.4.8279
    release: octopus-deploy
    heritage: Helm
spec:
  selector:
    matchLabels:
      app: octopus-deploy
      release: octopus-deploy
  serviceName: octopus-deploy
  replicas: 1
  template:
    metadata:
      labels:
        app: octopus-deploy
        release: octopus-deploy
    spec:
      serviceAccount: default
      containers:
              - name: octopus
                image: "octopusdeploy/octopusdeploy:2024.1.12163"
                securityContext:
                  privileged: true
                **env:
                  - name: ACCEPT_EULA
                    value: Y** 
```

Can you fix this?
